### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by jherdman**
Does what it says on the tin. Keepin' up with the keepin' up.

### CODE REVIEW

**Comment by jherdman** [comment]
Ping @cibernox

**Comment by jherdman** [comment]
Do you need help maintaining this lib? I'm more than happy to lend a hand.

**Comment by jherdman** [comment]
@cibernox sorry to pester, but is there any way you'd be able to take a look at this PR?

**Review by cibernox — APPROVED** [review]

**Comment by cibernox** [comment]
I completely missed this one. Sorry about that.

**Pull request merged**
