### PR TITLE
Update ember and other dependencies

### PR DESCRIPTION
**Pull request by markusm7**
Did an ember-cli-update and updated the versions of ember-power-calendar and ember-basic-dropdown.

In addition updated the version of the ember-power-calendar-moment

### CODE REVIEW

**Comment by cibernox** [comment]
LGTM, if Travis gets green let's merge this and release a new version

**Comment by cibernox** [comment]
IDK why travis is still pending but all checks are green, so I'll merge this

**Comment by cibernox** [comment]
Released 0.6.0

**Comment by markusm7** [comment]
Thank you, going to close my initial issue

**Pull request merged**
