### PR TITLE
Update ember v3.22.0...v3.28.5 & dependencies

### PR DESCRIPTION
**Pull request by mkszepp**
* Update Ember v3.22.0...v3.28.5
* `ember-basic-dropdown`: `^4.0.0`
* `ember-power-calendar`: `git+https://github.com/mkszepp/ember-power-calendar#e737658906e8521f06ff8c63da526a1a7a0cc077`
* `ember-power-calendar-moment`: `^0.2.0`
* Fix `#with` deprecation
* Fix some test warnings

remove dependency:
- `"ember-decorators": "^6.1.1"`

Fix for https://github.com/cibernox/ember-power-datepicker/issues/70

### CODE REVIEW

**Comment by mkszepp** [comment]
@cibernox now this changed are also ready for merge. Fix dependencies for ember 4

**Comment by mkszepp** [comment]
@cibernox is there possible to merge this changes?

**Comment by mkszepp** [comment]
The package is now updated for `ember-basic-dropdown` v6.x, but i was running in an other problem and the packages doesn't work again correctly in my app. All basic dropdowns are opend and can't be closed... :(.
I'm using embroider for build.

It looks like the package `ember-power-calendar` brings as dependency `ember-decorators` and this package is causing the problem. Maybe we should remove this dependency to solve the problem.

**Comment by mkszepp** [comment]
remove dependency:
- `"ember-decorators": "^6.1.1"`

update dependency:
- `"ember-power-calendar": "git+https://github.com/mkszepp/ember-power-calendar#e737658906e8521f06ff8c63da526a1a7a0cc077"`

We must wait for pull request close (https://github.com/cibernox/ember-power-calendar/pull/303). than there is possible to merge this changes.

**Comment by mkszepp** [comment]
- Updated `ember-power-calendar`, now there is possible to use embroider `staticComponents` in consuming app
- allow `ember-basic-dropdown` v7.x s dependency
- add `ensure-safe-component` in component helper to allow `staticComponents` for embroider build

**Comment by mkszepp** [comment]
@cibernox attention... we need to release `ember-power-datepicker` and than update this line: https://github.com/cibernox/ember-power-datepicker/blob/master/package.json#L38

**Comment by cibernox** [comment]
I'm on it

**Comment by cibernox** [comment]
Updated and published.

**Comment by mkszepp** [comment]
thank you

**Pull request merged**
